### ISSUE TITLE
When to end game and remove player

### ISSUE THREAD

**Issue by TheSTiana** [inf112-v20/biblioteket#131]
Problem with two players:
If player one has -1 lives the player are still dealt cards and the robot continue to move as long as player two has lives left.

**Comment by TheSTiana** [comment]
Either player two should be named winner or player one should be removed and player two can continue to play (alone).

**Comment by TheSTiana** [comment]
Noen har allerede laget en fiks som tar hensyn til spillere, men ikke til AI.

**Comment by sondr3** [comment]
@MarcusAadnekvam
