### ISSUE TITLE
Cards are not handled correctly after merge

### ISSUE THREAD

**Issue by TheSTiana** [inf112-v20/biblioteket#136]
Fikk denne feilmeldingen:

> No cards to draw, it is possible that the drawCards method is not followed by addToDiscardPile or that all the cards are stuck in the register.

Den utløses når `drawPile.isEmpty() && discardPile.isEmpty()`
Se linje 60 og 61 i Carddeck.

**Comment by TheSTiana** [comment]
Believe it to be because EasyAI draws cards, but never places them in discard pile.

**Comment by sondr3** [comment]
Ah, smart, tenkte at den draw funksjonen egentlig gjorde det. Skal ta en titt på det.
