### ISSUE TITLE
Move method must check if robot falls down hole or out of bounds

### ISSUE THREAD

**Issue by MarcusAadnekvam** [inf112-v20/biblioteket#86]
Doing so makes a player lose a life, not adding damage token to robot

**Comment by TheSTiana** [comment]
Mine checks if it goes out of bounds but not holes. Not sure what to do when player loses their last life.

**Comment by sondr3** [comment]
I'll fix.

**Comment by sondr3** [comment]
Nevermind, this has already been fixed as the game loop runs `interact` and a hole is "interactive".
